gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:              Yuchen Li
tagline:             'Home page'
description:         'Yuchen Li`s space in the Internet'
url:                 http://yuchen2017.github.io
baseurl:             /
paginate:            3

# About/contact
author:
  name:              Yuchen Li
  email:             ychli@ucdavis.edu

# Custom vars
version:             1.0.0

contact:
  GitHub:            'https://github.com/yuchen2017'
